# Generated by Django 4.1.4 on 2022-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Governance', 'Governance'), ('Energy and Mining', 'Energy and Mining')], max_length=128)),
                ('affiliated_agency', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('project_start_time', models.DateField(default=django.utils.timezone.now)),
                ('project_completion_time', models.DateField(default=django.utils.timezone.now)),
                ('total_budget', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coor', models.FloatField()),
                ('y_coor', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='project.project')),
            ],
        ),
    ]
