# Generated by Django 4.1.4 on 2022-12-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='affiliated_agency',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Governance', 'Governance'), ('Energy and Mining', 'Energy and Mining')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
